name: menthee_flutter_project
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^1.0.0
  flutter_riverpod: ^2.2.0
  go_router: ^6.0.6
  sqflite: ^2.2.4+1
  path: ^1.8.2
  path_provider: ^2.0.15
  intl: ^0.18.0
  mobile_number: ^2.1.1
  # print_bluetooth_thermal: ^1.0.5
  device_info_plus: ^9.0.2
  pointycastle: ^3.6.2
  either_dart: ^0.3.0
  equatable: ^2.0.5
  flutter_native_splash: ^2.2.18
  connectivity_plus: ^3.0.3
  shared_preferences: ^2.0.20
  pdf: ^3.10.1
  url_launcher: ^6.1.10
  external_path: ^1.0.3
  excel: ^2.1.0
  android_id: ^0.2.0
  sunmi_printer_plus: ^2.1.01
  dropdown_search: ^5.0.6
  dropdown_button2: ^2.1.0
  flutter_local_notifications: ^14.0.0+1
  permission_handler: ^10.2.0
  file_picker: ^5.2.11
  open_filex: ^4.3.2
  timeago: ^3.4.0
  shimmer: ^3.0.0
  change_app_package_name: ^1.1.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:       # use this websit to get icons https://icon.kitchen/
  color: "#006334" 
  # image: assets/images/repco_1.png
  # branding: assets/images/repco_1.png
  color_dark: "#006334" 
  # image_dark: assets/images/repco_1.png
  # branding_dark: assets/images/repco_1.png

  android_12:
    # image: assets/images/repco_1.png
    icon_background_color: "#ffffff"
    # image_dark: assets/logo-development.png
    # icon_background_color_dark: "#121212"
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/Helvetica.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
